project:
  type: website
  output-dir: docs
  resources: 
      - "personal_website/Swank_Elin_Resume_CV_ copy.pdf"

execute:
  freeze: auto

website:
  title: "wander-13"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd

format:
  html:
    theme:
      - custom_theme.scss
    css: styles.css
    toc: true

editor: visual

